import enum


class CollectionType(str, enum.Enum):
    COMPANY = "COMPANY"
    AUTHORITY = "AUTHORITY"
    THIRD_PARTY = "THIRD_PARTY"
    COMPETITOR = "COMPETITOR"


class AuthorityLevel(str, enum.Enum):
    LEVEL_1_CONTROLLED_COMPANY_OR_BINDING_AUTHORITY = "1_CONTROLLED_COMPANY_OR_BINDING_AUTHORITY"
    LEVEL_2_VERIFIED_INTERNAL_EVIDENCE = "2_VERIFIED_INTERNAL_EVIDENCE"
    LEVEL_3_OFFICIAL_EXTERNAL_AUTHORITY = "3_OFFICIAL_EXTERNAL_AUTHORITY"
    LEVEL_4_WORKING_DRAFT = "4_WORKING_DRAFT"
    LEVEL_5_SECONDARY_OR_ANALOG = "5_SECONDARY_OR_ANALOG"


class ParseStatus(str, enum.Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    QUARANTINED = "QUARANTINED"


class EmbeddingStatus(str, enum.Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    STALE = "STALE"


class ConfidentialityLevel(str, enum.Enum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    RESTRICTED = "RESTRICTED"


class JobStatus(str, enum.Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    # quick_scan only (see migration 0012): a name-only submission pauses
    # here after retrieval, before Stage 3, for the user to confirm or
    # correct the resolved identity. Never used for Job/CrawlSnapshot rows --
    # only the analysis_status Postgres enum type actually carries this
    # value; adding it to the shared Python enum is just for typing/validation.
    AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"


class RobotsStatus(str, enum.Enum):
    ALLOWED = "ALLOWED"
    DISALLOWED = "DISALLOWED"
    UNKNOWN = "UNKNOWN"


class FindingDomain(str, enum.Enum):
    PRODUCT_DEFINITION = "PRODUCT_DEFINITION"
    FDA_REGULATORY = "FDA_REGULATORY"
    CLINICAL_EVIDENCE = "CLINICAL_EVIDENCE"
    QUALITY_SYSTEM = "QUALITY_SYSTEM"
    MARKETING = "MARKETING"
    CODING = "CODING"
    COVERAGE = "COVERAGE"
    PAYMENT = "PAYMENT"
    BILLING = "BILLING"
    PROVIDER_ECONOMICS = "PROVIDER_ECONOMICS"
    MANUFACTURER_ECONOMICS = "MANUFACTURER_ECONOMICS"
    FRAUD_ABUSE = "FRAUD_ABUSE"
    PRIVACY = "PRIVACY"
    CYBERSECURITY = "CYBERSECURITY"
    RESEARCH_COMPLIANCE = "RESEARCH_COMPLIANCE"
    POSTMARKET = "POSTMARKET"


class EvidenceStatus(str, enum.Enum):
    VERIFIED = "VERIFIED"
    LIKELY = "LIKELY"
    CONDITIONAL = "CONDITIONAL"
    UNRESOLVED = "UNRESOLVED"
    MISSING = "MISSING"
    CONFLICTING = "CONFLICTING"
    STALE = "STALE"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class Verdict(str, enum.Enum):
    GO = "GO"
    CONDITIONAL_GO = "CONDITIONAL_GO"
    STOP = "STOP"


class RiskLevel(str, enum.Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ComplianceIssueStatus(str, enum.Enum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"


class CitationRole(str, enum.Enum):
    COMPANY_EVIDENCE = "COMPANY_EVIDENCE"
    CONTROLLING_AUTHORITY = "CONTROLLING_AUTHORITY"
    SUPPORTING_AUTHORITY = "SUPPORTING_AUTHORITY"
    CONTRADICTORY_EVIDENCE = "CONTRADICTORY_EVIDENCE"
    SECONDARY_CONTEXT = "SECONDARY_CONTEXT"


class ClaimCategory(str, enum.Enum):
    PRODUCT_CONFIGURATION = "PRODUCT_CONFIGURATION"
    TECHNICAL_CAPABILITY = "TECHNICAL_CAPABILITY"
    TECHNICAL_PERFORMANCE = "TECHNICAL_PERFORMANCE"
    ALGORITHMIC = "ALGORITHMIC"
    CLINICAL_PERFORMANCE = "CLINICAL_PERFORMANCE"
    SAFETY = "SAFETY"
    EFFECTIVENESS = "EFFECTIVENESS"
    DIAGNOSTIC = "DIAGNOSTIC"
    SCREENING = "SCREENING"
    MONITORING = "MONITORING"
    TREATMENT = "TREATMENT"
    CLINICAL_UTILITY = "CLINICAL_UTILITY"
    HEALTH_OUTCOME = "HEALTH_OUTCOME"
    WORKFLOW = "WORKFLOW"
    ECONOMIC = "ECONOMIC"
    ACCESS = "ACCESS"
    EQUITY = "EQUITY"
    COMPARISON = "COMPARISON"
    SUPERIORITY = "SUPERIORITY"
    REGULATORY_STATUS = "REGULATORY_STATUS"
    TRIAL_STATUS = "TRIAL_STATUS"
    AVAILABILITY = "AVAILABILITY"
    PRICING = "PRICING"
    COVERAGE = "COVERAGE"
    CODING = "CODING"
    PAYMENT = "PAYMENT"
    ENDORSEMENT = "ENDORSEMENT"
    TESTIMONIAL = "TESTIMONIAL"
    THIRD_PARTY_STATISTIC = "THIRD_PARTY_STATISTIC"
    DISEASE_AWARENESS = "DISEASE_AWARENESS"
    FUTURE_LOOKING = "FUTURE_LOOKING"


class ExpressOrImplied(str, enum.Enum):
    EXPRESS = "EXPRESS"
    IMPLIED = "IMPLIED"
    BOTH = "BOTH"


class ClaimDisposition(str, enum.Enum):
    RETAIN = "RETAIN"
    QUALIFY = "QUALIFY"
    REWRITE = "REWRITE"
    REMOVE = "REMOVE"
    QUARANTINE = "QUARANTINE"


class CodingEligibilityStatus(str, enum.Enum):
    POTENTIALLY_ALIGNED = "POTENTIALLY_ALIGNED"
    CONDITIONALLY_ALIGNED = "CONDITIONALLY_ALIGNED"
    NOT_CURRENTLY_SUPPORTED = "NOT_CURRENTLY_SUPPORTED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    EXPERT_REVIEW_REQUIRED = "EXPERT_REVIEW_REQUIRED"


class CitationVerificationStatus(str, enum.Enum):
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    FAILED = "FAILED"
