"""Gathers everything a report (Markdown/HTML/PDF/JSON) needs into plain
dataclasses, decoupled from the ORM so the report builders don't need a
live session and can be unit-tested with fixtures."""

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.models.analysis import AnalysisRun, Finding
from app.models.coding import CodingCandidate
from app.models.company import Company
from app.models.product import Product
from app.models.project import Project
from app.models.source_document import SourceDocument

# Domain display order mirrors build spec §22's report section order.
DOMAIN_ORDER = [
    "PRODUCT_DEFINITION",
    "FDA_REGULATORY",
    "CLINICAL_EVIDENCE",
    "QUALITY_SYSTEM",
    "CYBERSECURITY",
    "CODING",
    "COVERAGE",
    "PAYMENT",
    "BILLING",
    "PROVIDER_ECONOMICS",
    "MANUFACTURER_ECONOMICS",
    "MARKETING",
    "FRAUD_ABUSE",
    "PRIVACY",
    "RESEARCH_COMPLIANCE",
    "POSTMARKET",
]

RISK_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}


@dataclass
class ReportCitation:
    role: str
    quoted_text: str | None
    section_title: str | None
    page_number: int | None
    # Resolved server-side from the cited SourceDocument's own url field --
    # never generated by the LLM (see app/services/analysis/pipeline.py
    # ::_resolve_citations). None means no verified URL is on file yet.
    url: str | None = None
    document_title: str | None = None


@dataclass
class ReportSource:
    """One row in the report's final Sources section -- a distinct document
    that backed at least one citation in this analysis run."""

    title: str
    issuer: str | None
    jurisdiction: str | None
    authority_level: str | None
    url: str | None


@dataclass
class ReportFinding:
    domain: str
    title: str
    description: str
    status: str
    risk: str
    verdict: str | None
    verified_fact: str | None
    missing_information: list[str]
    applicable_requirement: str | None
    recommended_action: str | None
    responsible_owner: str | None
    priority: int | None
    confidence: int | None
    human_review_required: bool
    citations: list[ReportCitation]


@dataclass
class ReportCodingRequirement:
    requirement_name: str
    requirement_text: str
    status: str
    gap: str | None


@dataclass
class ReportCodingCandidate:
    code_system: str
    code: str | None
    code_year: str | None
    service_definition: str
    eligibility_status: str
    coverage_status: str | None
    payment_status: str | None
    billing_status: str | None
    major_gaps: list[str]
    expert_review_required: bool
    requirements: list[ReportCodingRequirement]


@dataclass
class ReportData:
    analysis_id: str
    company_name: str
    product_name: str | None
    jurisdiction: str | None
    analysis_model: str | None
    model_response_identifier: str | None
    source_cutoff_date: str | None
    overall_verdict: str | None
    overall_risk: str | None
    readiness_score: int | None
    readiness_score_note: str | None
    confidence_score: int | None
    executive_summary: str | None
    critical_blockers: list[str]
    missing_inputs: list[str]
    priority_actions: list[str]
    required_reviewers: list[str]
    findings: list[ReportFinding]
    coding_candidates: list[ReportCodingCandidate]
    sources: list[ReportSource] = field(default_factory=list)
    generated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def findings_by_domain(self) -> dict[str, list[ReportFinding]]:
        grouped: dict[str, list[ReportFinding]] = {}
        for finding in self.findings:
            grouped.setdefault(finding.domain, []).append(finding)
        return grouped

    def findings_by_priority(self) -> list[ReportFinding]:
        return sorted(
            self.findings,
            key=lambda f: (RISK_ORDER.get(f.risk, 99), f.priority if f.priority is not None else 99),
        )


async def gather_report_data(db: AsyncSession, analysis_run_id: uuid.UUID) -> ReportData | None:
    analysis_run = await db.get(AnalysisRun, analysis_run_id)
    if analysis_run is None:
        return None

    project = await db.get(Project, analysis_run.project_id)
    company = await db.get(Company, project.company_id) if project else None
    product = await db.get(Product, analysis_run.product_id) if analysis_run.product_id else None

    finding_rows = (
        await db.execute(
            select(Finding)
            .options(selectinload(Finding.citations))
            .where(Finding.analysis_run_id == analysis_run_id)
            .order_by(Finding.priority.nulls_last(), Finding.created_at)
        )
    ).scalars().all()

    cited_document_ids = {
        c.document_id for f in finding_rows for c in f.citations if c.document_id is not None
    }
    cited_documents: dict[uuid.UUID, SourceDocument] = {}
    if cited_document_ids:
        doc_rows = (
            await db.execute(select(SourceDocument).where(SourceDocument.id.in_(cited_document_ids)))
        ).scalars().all()
        cited_documents = {d.id: d for d in doc_rows}

    findings = [
        ReportFinding(
            domain=f.domain.value,
            title=f.title,
            description=f.description,
            status=f.status,
            risk=f.risk.value,
            verdict=f.verdict.value if f.verdict else None,
            verified_fact=f.verified_fact,
            missing_information=f.missing_information,
            applicable_requirement=f.applicable_requirement,
            recommended_action=f.recommended_action,
            responsible_owner=f.responsible_owner,
            priority=f.priority,
            confidence=f.confidence,
            human_review_required=f.human_review_required,
            citations=[
                ReportCitation(
                    role=c.citation_role.value,
                    quoted_text=c.quoted_text,
                    section_title=c.section_title,
                    page_number=c.page_number,
                    # c.url is already resolved server-side at citation-creation
                    # time (see pipeline.py::_resolve_citations); re-deriving it
                    # here from the joined SourceDocument as a fallback covers
                    # citations created before that field existed.
                    url=c.url or (cited_documents[c.document_id].url if c.document_id in cited_documents else None),
                    document_title=cited_documents[c.document_id].title if c.document_id in cited_documents else None,
                )
                for c in f.citations
            ],
        )
        for f in finding_rows
    ]

    sources = sorted(
        (
            ReportSource(
                title=d.title,
                issuer=d.issuer,
                jurisdiction=d.jurisdiction,
                authority_level=d.authority_level.value if d.authority_level else None,
                url=d.url,
            )
            for d in cited_documents.values()
        ),
        key=lambda s: (s.authority_level or "9", s.title),
    )

    candidate_rows = (
        await db.execute(
            select(CodingCandidate)
            .options(selectinload(CodingCandidate.requirements))
            .where(CodingCandidate.analysis_run_id == analysis_run_id)
        )
    ).scalars().all()

    coding_candidates = [
        ReportCodingCandidate(
            code_system=c.code_system,
            code=c.code,
            code_year=c.code_year,
            service_definition=c.service_definition,
            eligibility_status=c.eligibility_status.value,
            coverage_status=c.coverage_status,
            payment_status=c.payment_status,
            billing_status=c.billing_status,
            major_gaps=c.major_gaps,
            expert_review_required=c.expert_review_required,
            requirements=[
                ReportCodingRequirement(
                    requirement_name=r.requirement_name,
                    requirement_text=r.requirement_text,
                    status=r.status,
                    gap=r.gap,
                )
                for r in c.requirements
            ],
        )
        for c in candidate_rows
    ]

    return ReportData(
        analysis_id=str(analysis_run.id),
        company_name=company.name if company else "Unknown company",
        product_name=product.name if product else None,
        jurisdiction=project.jurisdiction if project else None,
        analysis_model=analysis_run.analysis_model,
        model_response_identifier=analysis_run.model_response_identifier,
        source_cutoff_date=analysis_run.source_cutoff_date.isoformat() if analysis_run.source_cutoff_date else None,
        overall_verdict=analysis_run.overall_verdict.value if analysis_run.overall_verdict else None,
        overall_risk=analysis_run.overall_risk.value if analysis_run.overall_risk else None,
        readiness_score=analysis_run.readiness_score,
        readiness_score_note=analysis_run.readiness_score_note,
        confidence_score=analysis_run.confidence_score,
        executive_summary=analysis_run.executive_summary,
        critical_blockers=analysis_run.critical_blockers,
        missing_inputs=analysis_run.missing_inputs,
        priority_actions=analysis_run.priority_actions,
        required_reviewers=analysis_run.required_reviewers,
        findings=findings,
        coding_candidates=coding_candidates,
        sources=sources,
    )
